!
!  SPDX-License-Identifier: GPL-3.0-or-later
!  Copyright (C) 2019-2022, respective authors of MCFM.
!

c********************************************************
cAUTHOR: FABIO MALTONI                                  *
cDATE  : 2/15/2003                                     *
cNOTES : PROGRAM GENERATED BY ToFortran.m               *
c        AMPLITUDES CALCULATED BY ALBERTO FRIZZO        *
c********************************************************

      function  Appppp(I1,I2,I3,I4,I5)
c ---------------------------------------------------------------------
c                            1+ 2+ 3+ 4+ 5+
c ---------------------------------------------------------------------
      IMPLICIT NONE
      include 'types.f'
      complex(dp) Appppp

      include 'mxpart.f'
      include 'sprods_com.f'
      include 'zprods_com.f'
      integer::I1,I2,I3,I4,I5
      real(dp)::MSQ

      MSQ=
     & +s(i1,i2)+s(i1,i3)+s(i1,i4)+s(i1,i5)
     &          +s(i2,i3)+s(i2,i4)+s(i2,i5)
     &                   +s(i3,i4)+s(i3,i5)
     &                            +s(i4,i5)

      Appppp=MSQ**2/(za(i1,i2)*za(i2,i3)*za(i3,i4)*za(i4,i5)*za(i5,i1))

      END

